# Generated by Django 4.0.5 on 2022-11-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Challenges_solve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('Challenge_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Web_Challenges_solved',
        ),
    ]
