# Generated by Django 3.1.6 on 2021-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptography_challenges',
            name='Challenge_File',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
