# Generated by Django 3.1.6 on 2021-04-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptography', '0002_auto_20210427_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptography_challenges',
            name='Challenge_Ratings',
            field=models.IntegerField(default=2.5),
        ),
    ]
